semantic_color_mode: "semantic"
semantic_measurement_probability: 0.6
dynamic_semantic_labels: [19,20]
min_time_between_msgs_sec: 0.5
update_mesh_every_n_sec: 5.0
# max_block_distance_from_body: 10
tsdf_voxel_size: 0.20
max_ray_length_m: 4