semantic_color_mode: "semantic"
semantic_measurement_probability: 0.8
dynamic_semantic_labels: [20]
min_time_between_msgs_sec: 0.2
update_mesh_every_n_sec: 1.0
# max_block_distance_from_body: 1000
tsdf_voxel_size: 0.05
max_ray_length_m: 5